# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"\x1f\n\x0cStockRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"3\n\rStockResponse\x12\x10\n\x08in_stock\x18\x01 \x01(\x08\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x32\x38\n\tInventory\x12+\n\nCheckStock\x12\r.StockRequest\x1a\x0e.StockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STOCKREQUEST']._serialized_start=19
  _globals['_STOCKREQUEST']._serialized_end=50
  _globals['_STOCKRESPONSE']._serialized_start=52
  _globals['_STOCKRESPONSE']._serialized_end=103
  _globals['_INVENTORY']._serialized_start=105
  _globals['_INVENTORY']._serialized_end=161
# @@protoc_insertion_point(module_scope)
